# Generated by Django 4.2.4 on 2023-09-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0003_stationary_cost_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationary',
            name='cost_per_unit',
        ),
    ]
