# Generated by Django 4.2.4 on 2023-09-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0004_remove_stationary_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationary',
            name='cost_per_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
