# Generated by Django 4.2.4 on 2023-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0005_stationary_cost_per_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyrequest',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='facultyrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Seen', 'Seen'), ('Issued', 'Issued'), ('Ordered', 'Ordered')], default='Pending', max_length=10),
        ),
    ]
