# Generated by Django 4.2.4 on 2023-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0006_remove_facultyrequest_fulfilled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
