# Generated by Django 4.2.4 on 2023-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0008_stationarybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationarybill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
