# Generated by Django 4.2.4 on 2023-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0010_alter_assignment_id_alter_faculty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
    ]
