# Generated by Django 4.2.4 on 2024-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0012_faculty_faculty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_email',
            field=models.CharField(max_length=100),
        ),
    ]
