# Generated by Django 4.2.4 on 2024-02-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0013_alter_faculty_faculty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationarybill',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
