# Generated by Django 4.2.4 on 2024-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0014_alter_stationarybill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationarybill',
            name='caption',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stationarybill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stationarybill',
            name='image',
            field=models.BinaryField(),
        ),
    ]
