# Generated by Django 4.2.4 on 2024-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0018_assignment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.CharField(default='DEPT', max_length=30),
        ),
    ]
