# Generated by Django 4.2.4 on 2024-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0019_alter_assignment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyrequest',
            name='note',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
