# Generated by Django 4.2.4 on 2024-02-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0021_customuser_is_google_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_google_user',
        ),
    ]
