# Generated by Django 4.2.4 on 2024-03-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0023_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('admin', 'Admin')], max_length=20),
        ),
    ]
