# Generated by Django 4.2.4 on 2024-03-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationaryapp', '0024_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationary',
            name='available_quantity',
        ),
    ]
